import { Artifact, WorkflowStep } from '@/types/run';
import { cn } from '@/lib/utils';
import { FileCode, FileJson, FileText, Server, Check, X, Clock } from 'lucide-react';
import { useState } from 'react';

interface ArtifactsViewerProps {
  artifacts: Artifact[];
}

const typeIcons: Record<Artifact['type'], typeof FileCode> = {
  spec: FileJson,
  code: FileCode,
  test: FileText,
  infra: Server,
};

const typeLabels: Record<Artifact['type'], string> = {
  spec: 'Specifications',
  code: 'App Code',
  test: 'Tests',
  infra: 'Infrastructure',
};

export function ArtifactsViewer({ artifacts }: ArtifactsViewerProps) {
  const [selectedArtifact, setSelectedArtifact] = useState<Artifact | null>(
    artifacts.length > 0 ? artifacts[0] : null
  );

  const groupedArtifacts = artifacts.reduce((acc, artifact) => {
    if (!acc[artifact.type]) acc[artifact.type] = [];
    acc[artifact.type].push(artifact);
    return acc;
  }, {} as Record<Artifact['type'], Artifact[]>);

  if (artifacts.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <FileCode className="h-10 w-10 text-muted-foreground mb-3" />
        <p className="text-sm text-muted-foreground">No artifacts generated yet</p>
      </div>
    );
  }

  return (
    <div className="flex gap-4 h-[400px]">
      {/* File Tree */}
      <div className="w-64 shrink-0 border border-border rounded-lg bg-card overflow-hidden">
        <div className="p-3 border-b border-border">
          <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
            Files
          </p>
        </div>
        <div className="p-2 space-y-4 overflow-auto max-h-[calc(400px-48px)]">
          {Object.entries(groupedArtifacts).map(([type, files]) => {
            const Icon = typeIcons[type as Artifact['type']];
            return (
              <div key={type}>
                <div className="flex items-center gap-2 px-2 py-1 text-xs text-muted-foreground uppercase tracking-wider">
                  <Icon className="h-3 w-3" />
                  {typeLabels[type as Artifact['type']]}
                </div>
                <div className="space-y-0.5">
                  {files.map((file) => (
                    <button
                      key={file.id}
                      onClick={() => setSelectedArtifact(file)}
                      className={cn(
                        'w-full text-left px-2 py-1.5 rounded text-sm transition-colors',
                        selectedArtifact?.id === file.id
                          ? 'bg-primary/10 text-primary'
                          : 'text-foreground hover:bg-muted'
                      )}
                    >
                      <span className="truncate block font-mono text-xs">{file.name}</span>
                    </button>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Code Viewer */}
      <div className="flex-1 border border-border rounded-lg bg-card overflow-hidden flex flex-col">
        {selectedArtifact ? (
          <>
            <div className="p-3 border-b border-border flex items-center justify-between">
              <div>
                <p className="text-sm font-mono text-foreground">{selectedArtifact.name}</p>
                <p className="text-xs text-muted-foreground mt-0.5">
                  Generated by {selectedArtifact.generatedBy.replace('_', ' ')}
                </p>
              </div>
              <ValidationStatus status={selectedArtifact.validationStatus} />
            </div>
            <pre className="flex-1 p-4 overflow-auto text-xs font-mono text-foreground bg-background/50">
              <code>{selectedArtifact.content}</code>
            </pre>
          </>
        ) : (
          <div className="flex-1 flex items-center justify-center">
            <p className="text-sm text-muted-foreground">Select a file to view</p>
          </div>
        )}
      </div>
    </div>
  );
}

function ValidationStatus({ status }: { status: Artifact['validationStatus'] }) {
  switch (status) {
    case 'valid':
      return (
        <span className="flex items-center gap-1.5 text-xs text-success bg-success/10 px-2 py-1 rounded">
          <Check className="h-3 w-3" />
          Valid
        </span>
      );
    case 'invalid':
      return (
        <span className="flex items-center gap-1.5 text-xs text-destructive bg-destructive/10 px-2 py-1 rounded">
          <X className="h-3 w-3" />
          Invalid
        </span>
      );
    default:
      return (
        <span className="flex items-center gap-1.5 text-xs text-muted-foreground bg-muted px-2 py-1 rounded">
          <Clock className="h-3 w-3" />
          Pending
        </span>
      );
  }
}
